services:
  node1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ./node
    container_name: node1
    environment:
      - NODE_ID=Node-1
      - PORT=50051
      - PEERS=node2:50052
    ports:
      - "50051:50051"

  node2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ./node
    container_name: node2
    environment:
      - NODE_ID=Node-2
      - PORT=50052
      - PEERS=node1:50051
    ports:
      - "50052:50052"